# Generated by Django 6.0 on 2026-01-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_invoice_issued_at_invoice_issued_by_invoice_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("wechat", "WeChat Pay"),
                    ("alipay", "Alipay"),
                    ("unionpay", "UnionPay"),
                    ("visa", "Visa"),
                    ("mastercard", "Mastercard"),
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("insurance", "Insurance"),
                ],
                default="wechat",
                max_length=16,
            ),
        ),
    ]
