# Generated by Django 6.0 on 2026-01-01 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_no", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("doctor", "Doctor"),
                            ("nurse", "Nurse"),
                            ("pharmacist", "Pharmacist"),
                            ("finance", "Finance"),
                            ("admin", "Admin"),
                        ],
                        default="doctor",
                        max_length=16,
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, default="General", max_length=64),
                ),
                ("position", models.CharField(blank=True, default="", max_length=64)),
                ("specialty", models.CharField(blank=True, default="", max_length=128)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
