# Generated by Django 6.0 on 2026-01-01 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('specification', models.CharField(blank=True, default='', max_length=128)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('warning_level', models.IntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pharmacy.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_no', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prescription', to='patients.visit')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dosage', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription')),
            ],
            options={
                'unique_together': {('prescription', 'drug')},
            },
        ),
    ]
